version: 2
jobs:
  test:
    docker:
      - image: ehdevops/ruby240:latest
    working_directory: ~/xero_gateway
    steps:
      - checkout
      - run: cp *.gemspec gemspec
      - restore_cache:
          keys:
            - bundle-caches{{ checksum "gemspec" }}
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundle-caches{{ checksum "gemspec" }}
          paths:
            - ~/xero_gateway/vendor/bundle
      - run: bundle exec rake test
  publish:
    docker:
      - image: ehdevops/ruby240:latest
    working_directory: ~/xero_gateway
    steps:
      - checkout
      - run: cp *.gemspec gemspec
      - restore_cache:
          keys:
            - bundle-caches{{ checksum "gemspec" }}
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundle-caches{{ checksum "gemspec" }}
          paths:
            - ~/xero_gateway/vendor/bundle
      - run: mkdir -p ./tmp/; mkdir -p ./tmp/cache
      - run: mkdir -p ./tmp/employment-hero/config/
      - run: echo -e "$PRIVATEKEY_PEM" > ./tmp/employment-hero/config/privatekey.pem
      - run: echo -e "$ENTRUST_CERT_PEM" > ./tmp/employment-hero/config/entrust-cert.pem
      - run: echo -e "$ENTRUST_PRIVATE_NOPASS_PEM" > ./tmp/employment-hero/config/entrust-private-nopass.pem
      - run: bundle exec ruby scripts/publish.rb

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - publish:
          context: org-global
          filters:
            branches:
              only:
                - master
          requires:
            - test
